version: "3.7"

services:
  nginx:
    image: nginx:1.24-alpine
    container_name: news_nginx
    restart: unless-stopped
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./app:/var/www/app
      - ./docker/nginx/log/:/var/log/nginx
    depends_on:
      - php
      - postgres

  php:
    build: ./docker/php
    container_name: news_php
    restart: unless-stopped
    volumes:
      - ./app:/var/www/app
      - ./docker/php/log:/var/log/php
    environment:
      COMPOSER_HOME: "/var/www/composer"
    extra_hosts:
      - "host.docker.internal:${DOCKER_HOST_IP}"
    depends_on:
      - postgres

  postgres:
    image: postgres:12.9
    container_name: news_postgres
    restart: unless-stopped
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data:rw
      - ./docker/postgresql/log:/var/log/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432

  mailcatcher:
    image: schickling/mailcatcher
    container_name: news_mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
